### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by alanwhyte** [SatyamSSJ10/Blender-Bulk-Texture-Replacer#1]
I cannot Install the addon, every time I try I get the same issue. I tried with different blender versions but I always get the same error.

File "D:\Blender\2.93\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'replacing'

**Comment by vsatyamesc** [comment]
Try extracting the .zip file if you downloaded the source code. and then install the python script.
Either way try to install through the python script. but it should work even with you install using the zip.

There can be other problems like Python-Blender incompatibility, or some really simple thing.

**Comment by alanwhyte** [comment]
Thanks, that fixed it. I downloaded the .py first but after downloading the .zip and extracting it worked.
