### ISSUE TITLE
Newest version wont work for me.

### ISSUE THREAD

**Issue by Luc69lol** [SatyamSSJ10/Blender-Bulk-Texture-Replacer#2]
I get this error every time I try to activate it
![image](https://github.com/SatyamSSJ10/Blender-Bulk-Texture-Replacer/assets/120069015/1a0de3a8-91e1-48bf-a32b-14ae684134ec)

**Comment by vsatyamesc** [comment]
Simple solution.

If you are using Zip to install, unpack the zip then rename the python file to replacing_addon.py "with _ " in the name and then zip it again to install. The thing here is to not include (space) in the name of file.

**Comment by m4rr5** [comment]
I would document this somewhere. I downloaded the py file directly from the release, and I also had to rename it from `replacing.addone.py` to `replacing_addone.py` to make it work in Blender 4.
